spring:  
  main:    
    allow-bean-definition-overriding: true
    banner-mode: "off"
  # Database  
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ProviviTest
    username: proviviuser
    password: provivi_pass

  jpa:
    hibernate:      
      ddl-auto: create
      show-sql: false
      properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  thymeleaf:
     cache: false